# https://shift.click/blog/github-actions-rust/#quick-setup--overview
name: CI
# Runs on all PRs and pushes to any branch. See the section
# on event hooks for other options.
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v2      
      - name: Install Rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - run: cargo build
      - run: cargo test --verbose

